# Generated by Django 6.0.6 on 2026-06-26 11:29

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referentiels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametresBudget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('jour_debut_mois_comptable', models.PositiveSmallIntegerField(default=1, help_text='Jour du mois où débute le mois comptable (1 = mois calendaire). Borné à 28 pour rester valide tous les mois. Ex. 25 : la période du 25 au 24 du mois suivant est le mois comptable du suivant.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)])),
            ],
            options={
                'verbose_name': 'Paramètres budget',
                'verbose_name_plural': 'Paramètres budget',
            },
        ),
    ]
