# Generated by Django 6.0.6 on 2026-07-06 11:24

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referentiels', '0003_parametresbudget_valeur_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametresbudget',
            name='valeur_point',
            field=models.DecimalField(decimal_places=2, default=Decimal('10'), help_text="Valeur d'un point de budget (mécanique B — système de points). En € : combien d'euros sous/sur-consommés valent un point. Défaut 10 €.", max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
