# Generated by Django 6.0.6 on 2026-07-18 08:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referentiels', '0004_alter_parametresbudget_valeur_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametresbudget',
            name='tolerance_jours_rapprochement',
            field=models.PositiveSmallIntegerField(default=3, help_text="Fenêtre de tolérance (en jours) pour rapprocher une ligne de relevé bancaire d'un flux de l'app : la date carte diffère souvent de la date d'opération. Défaut 3 jours.", validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(31)]),
        ),
    ]
