# Generated by Django 6.0.6 on 2026-06-08 20:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('referentiels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('code', models.CharField(help_text='Code unique du compte (ex: CPT-0001)', max_length=20, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('solde_initial', models.DecimalField(decimal_places=2, default=0, help_text="Solde au moment de la création du compte dans l'application", max_digits=12)),
                ('solde_reel', models.DecimalField(decimal_places=2, default=0, help_text='Solde réel constaté (saisi manuellement ou via import bancaire)', max_digits=12)),
                ('solde_theorique', models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Calculé : solde_initial + Σ flux. Jamais éditable.', max_digits=12)),
                ('ecart_solde', models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Calculé : solde_reel - solde_theorique. Jamais éditable.', max_digits=12)),
                ('actif', models.BooleanField(default=True)),
                ('date_ouverture', models.DateField(blank=True, null=True)),
                ('date_fermeture', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('devise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comptes', to='referentiels.devise')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comptes', to='referentiels.etablissement')),
                ('titulaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comptes', to='referentiels.titulaire')),
                ('type_compte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comptes', to='referentiels.typecompte')),
            ],
            options={
                'verbose_name': 'Compte',
                'verbose_name_plural': 'Comptes',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
