# Generated by Django 6.0.6 on 2026-06-18 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0002_compte_est_commun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compte',
            name='solde_reel',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Calculé : solde_initial + Σ(flux dont statut.est_definitif=True). Jamais éditable.', max_digits=12),
        ),
    ]
