# Generated by Django 6.0.6 on 2026-07-10 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0003_alter_compte_solde_reel'),
    ]

    operations = [
        migrations.AddField(
            model_name='compte',
            name='est_epargne',
            field=models.BooleanField(default=False, help_text="Compte d'épargne (livret, PEL, PEA…) — alimenté par transferts, suivi dans l'analyse de l'épargne. Purement informatif pour les soldes."),
        ),
        migrations.AddField(
            model_name='compte',
            name='taux_annuel',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Taux d'intérêt annuel en % (ex. 3.00 pour un Livret A). Informatif au MVP ; destiné à la projection des intérêts (prévisionnel, à venir).", max_digits=5, null=True),
        ),
    ]
