# Generated by Django 6.0.6 on 2026-07-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0005_init_est_epargne_from_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compte',
            name='code',
            field=models.CharField(help_text='Numéro de compte (ex: 00040553758 ou IBAN). Sert au rapprochement automatique des relevés bancaires.', max_length=34, unique=True),
        ),
    ]
