# Generated by Django 6.0.6 on 2026-06-08 21:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('mois', models.DateField(help_text='Premier jour du mois budgété (ex: 2024-03-01).')),
                ('montant_prevu', models.DecimalField(decimal_places=2, help_text='Enveloppe budgétaire prévue. Toujours positif.', max_digits=12)),
                ('montant_consomme', models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Calculé : somme des flux de dépense sur cette catégorie ce mois.', max_digits=12)),
                ('taux_consommation', models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Calculé : montant_consomme / montant_prevu * 100.', max_digits=6)),
                ('notes', models.TextField(blank=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='categories.categorie')),
            ],
            options={
                'verbose_name': 'Budget',
                'verbose_name_plural': 'Budgets',
                'ordering': ['-mois', 'categorie__nom'],
                'abstract': False,
                'indexes': [models.Index(fields=['mois'], name='budgets_bud_mois_f0b728_idx'), models.Index(fields=['categorie', 'mois'], name='budgets_bud_categor_2dd19a_idx')],
                'constraints': [models.UniqueConstraint(fields=('categorie', 'mois'), name='budget_unique_categorie_mois')],
            },
        ),
    ]
