# Generated by Django 6.0.6 on 2026-06-11 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='categories_incluses',
            field=models.ManyToManyField(blank=True, help_text='Sous-catégories incluses dans ce budget majeur (pertinent uniquement si est_budget_majeur=True).', related_name='budgets_incluant', to='categories.categorie'),
        ),
        migrations.AddField(
            model_name='budget',
            name='est_budget_majeur',
            field=models.BooleanField(default=False, help_text='True si la catégorie ciblée est une majeure (agrège les mineures incluses).'),
        ),
    ]
