# Generated by Django 6.0.6 on 2026-06-11 20:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0002_budget_categories_incluses_budget_est_budget_majeur'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('montant_defaut', models.DecimalField(decimal_places=2, help_text='Montant proposé à chaque reconduction. Toujours positif.', max_digits=12)),
                ('est_budget_majeur', models.BooleanField(default=False, help_text='Auto-détecté : True si la catégorie est une majeure avec mineures actives.')),
                ('actif', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_templates', to='categories.categorie')),
                ('categories_incluses', models.ManyToManyField(blank=True, help_text='Sous-catégories incluses (pertinent si est_budget_majeur=True).', related_name='budget_templates_incluant', to='categories.categorie')),
            ],
            options={
                'verbose_name': 'Modèle de budget',
                'verbose_name_plural': 'Modèles de budget',
                'ordering': ['categorie__nom'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='budget',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Template dont ce budget est issu. Null = budget ponctuel créé manuellement.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budgets_mensuels', to='budgets.budgettemplate'),
        ),
        migrations.AddConstraint(
            model_name='budgettemplate',
            constraint=models.UniqueConstraint(fields=('categorie',), name='budgettemplate_unique_categorie'),
        ),
    ]
