# Generated by Django 6.0.6 on 2026-06-11 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0003_budgettemplate_budget_template_and_more'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='budget',
            name='budget_unique_categorie_mois',
        ),
        migrations.RemoveConstraint(
            model_name='budgettemplate',
            name='budgettemplate_unique_categorie',
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('categorie', 'mois'), name='budget_unique_categorie_mois'),
        ),
        migrations.AddConstraint(
            model_name='budgettemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('categorie',), name='budgettemplate_unique_categorie'),
        ),
    ]
