# Generated by Django 6.0.6 on 2026-07-06 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0004_remove_budget_budget_unique_categorie_mois_and_more'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'ordering': ['-mois', 'categorie__nom', 'nom'], 'verbose_name': 'Budget', 'verbose_name_plural': 'Budgets'},
        ),
        migrations.AlterModelOptions(
            name='budgettemplate',
            options={'ordering': ['categorie__nom', 'nom'], 'verbose_name': 'Modèle de budget', 'verbose_name_plural': 'Modèles de budget'},
        ),
        migrations.RemoveConstraint(
            model_name='budget',
            name='budget_unique_categorie_mois',
        ),
        migrations.RemoveConstraint(
            model_name='budgettemplate',
            name='budgettemplate_unique_categorie',
        ),
        migrations.AddField(
            model_name='budget',
            name='nom',
            field=models.CharField(blank=True, help_text='Libellé du budget. Requis pour un budget thématique (categorie null).', max_length=120),
        ),
        migrations.AddField(
            model_name='budgettemplate',
            name='nom',
            field=models.CharField(blank=True, help_text='Libellé du modèle. Requis pour un budget thématique (categorie null).', max_length=120),
        ),
        migrations.AlterField(
            model_name='budget',
            name='categorie',
            field=models.ForeignKey(blank=True, help_text='Catégorie ancre (simple ou majeure). Null = budget thématique (voir nom).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='categories.categorie'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='categories_incluses',
            field=models.ManyToManyField(blank=True, help_text="Catégories couvertes (mineures d'une majeure, ou feuilles libres d'un thématique).", related_name='budgets_incluant', to='categories.categorie'),
        ),
        migrations.AlterField(
            model_name='budgettemplate',
            name='categorie',
            field=models.ForeignKey(blank=True, help_text='Catégorie ancre (simple ou majeure). Null = budget thématique (voir nom).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budget_templates', to='categories.categorie'),
        ),
        migrations.AlterField(
            model_name='budgettemplate',
            name='categories_incluses',
            field=models.ManyToManyField(blank=True, help_text="Catégories couvertes (mineures d'une majeure, ou feuilles libres d'un thématique).", related_name='budget_templates_incluant', to='categories.categorie'),
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.UniqueConstraint(condition=models.Q(('categorie__isnull', False), ('is_deleted', False)), fields=('categorie', 'mois'), name='budget_unique_categorie_mois'),
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.UniqueConstraint(condition=models.Q(('categorie__isnull', True), ('is_deleted', False)), fields=('nom', 'mois'), name='budget_unique_nom_mois_thematique'),
        ),
        migrations.AddConstraint(
            model_name='budgettemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('categorie__isnull', False), ('is_deleted', False)), fields=('categorie',), name='budgettemplate_unique_categorie'),
        ),
        migrations.AddConstraint(
            model_name='budgettemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('categorie__isnull', True), ('is_deleted', False)), fields=('nom',), name='budgettemplate_unique_nom_thematique'),
        ),
    ]
