# Generated by Django 6.0.6 on 2026-07-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0005_alter_budget_options_alter_budgettemplate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='en_jeu',
            field=models.BooleanField(default=False, help_text='Mécanique B (points) : cette enveloppe participe au calcul des points du mois (sous-consommé → gain, dépassé → perte).'),
        ),
        migrations.AddField(
            model_name='budget',
            name='points_alloues',
            field=models.PositiveIntegerField(default=0, help_text='Mécanique B (12-B-2) : points distribués depuis la réserve vers cette enveloppe. Prévu effectif = montant_prevu + points_alloues × valeur_point.'),
        ),
        migrations.AddField(
            model_name='budgettemplate',
            name='en_jeu',
            field=models.BooleanField(default=False, help_text="Mécanique B (points) : l'enveloppe participe au calcul des points. Reporté sur les budgets reconduits depuis ce modèle."),
        ),
    ]
