# Generated by Django 6.0.6 on 2026-06-08 20:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('comptes', '0001_initial'),
        ('referentiels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flux',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('montant', models.DecimalField(decimal_places=2, help_text='Montant signé : négatif = dépense, positif = recette.', max_digits=12)),
                ('date_flux', models.DateField(default=django.utils.timezone.now, help_text='Date réelle du mouvement.')),
                ('mois', models.DateField(editable=False, help_text='Premier jour du mois de date_flux. Calculé automatiquement.')),
                ('est_transfert', models.BooleanField(default=False, help_text="True si ce flux fait partie d'un transfert interne entre comptes.")),
                ('libelle', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('reference_externe', models.CharField(blank=True, help_text='Référence bancaire ou numéro de pièce.', max_length=100)),
                ('categorie', models.ForeignKey(blank=True, help_text='Null autorisé uniquement pour les transferts internes.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='flux', to='categories.categorie')),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flux', to='comptes.compte')),
                ('devise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flux', to='referentiels.devise')),
                ('mode_paiement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='flux', to='referentiels.modepaiement')),
                ('statut', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flux', to='referentiels.statutflux')),
                ('titulaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='flux', to='referentiels.titulaire')),
                ('type_flux', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flux', to='referentiels.typeflux')),
            ],
            options={
                'verbose_name': 'Flux',
                'verbose_name_plural': 'Flux',
                'ordering': ['-date_flux', '-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['compte', 'mois'], name='flux_flux_compte__b9db40_idx'), models.Index(fields=['compte', 'date_flux'], name='flux_flux_compte__8276e1_idx'), models.Index(fields=['categorie', 'mois'], name='flux_flux_categor_aee625_idx'), models.Index(fields=['est_transfert'], name='flux_flux_est_tra_295fdc_idx')],
            },
        ),
    ]
