# Generated by Django 6.0.6 on 2026-06-10 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('comptes', '0001_initial'),
        ('flux', '0001_initial'),
        ('referentiels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flux',
            name='est_ajustement',
            field=models.BooleanField(default=False, help_text='True si ce flux est un ajustement de solde généré par la réconciliation. Exclu de tous les agrégats dépenses/revenus.'),
        ),
        migrations.AddIndex(
            model_name='flux',
            index=models.Index(fields=['est_ajustement'], name='flux_flux_est_aju_85c9f0_idx'),
        ),
    ]
