# Generated by Django 6.0.6 on 2026-07-04 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonnements', '0001_initial'),
        ('flux', '0002_flux_est_ajustement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flux',
            name='abonnement',
            field=models.ForeignKey(blank=True, help_text="Abonnement d'origine si ce flux a été généré depuis le référentiel.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flux', to='abonnements.abonnement'),
        ),
    ]
