# Generated by Django 6.0.6 on 2026-07-23 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flux', '0003_flux_abonnement'),
    ]

    operations = [
        migrations.AddField(
            model_name='flux',
            name='flux_rembourse',
            field=models.ForeignKey(blank=True, help_text="Dépense d'origine remboursée par ce flux (contre-flux recette).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remboursements', to='flux.flux'),
        ),
    ]
