# Generated by Django 6.0.6 on 2026-06-09 07:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('comptes', '0001_initial'),
        ('referentiels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('nom', models.CharField(max_length=150)),
                ('montant_attendu', models.DecimalField(decimal_places=2, help_text='Montant signé de référence. Négatif = dépense, positif = recette.', max_digits=12)),
                ('seuil_divergence_pct', models.DecimalField(decimal_places=2, default=10, help_text='Écart en % au-delà duquel une divergence est signalée.', max_digits=5)),
                ('date_debut', models.DateField(help_text='Date du premier flux attendu.')),
                ('date_fin', models.DateField(blank=True, help_text='Date de fin. Null = sans fin définie.', null=True)),
                ('jour_echeance', models.PositiveSmallIntegerField(blank=True, help_text="Jour du mois de l'échéance habituelle (1-31).", null=True)),
                ('derniere_occurrence', models.DateField(blank=True, editable=False, help_text='Date du dernier flux rattaché à cet abonnement. Calculé.', null=True)),
                ('actif', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='abonnements', to='categories.categorie')),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abonnements', to='comptes.compte')),
                ('frequence', models.ForeignKey(help_text='Fréquence depuis le référentiel — jamais codée en dur.', on_delete=django.db.models.deletion.PROTECT, related_name='abonnements', to='referentiels.frequence')),
                ('mode_paiement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='abonnements', to='referentiels.modepaiement')),
                ('type_flux', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abonnements', to='referentiels.typeflux')),
            ],
            options={
                'verbose_name': 'Abonnement',
                'verbose_name_plural': 'Abonnements',
                'ordering': ['nom'],
                'abstract': False,
            },
        ),
    ]
