# Generated by Django 6.0.6 on 2026-06-09 07:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comptes', '0001_initial'),
        ('referentiels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actif',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('nom', models.CharField(max_length=150)),
                ('type_actif', models.CharField(choices=[('IMMOBILIER', 'Immobilier'), ('EPARGNE', 'Épargne bancaire'), ('PEA', 'PEA'), ('ASSURANCE_VIE', 'Assurance-vie'), ('COMPTE_TITRES', 'Compte-titres'), ('CRYPTO', 'Crypto-actifs'), ('AUTRE', 'Autre')], max_length=30)),
                ('valeur_acquisition', models.DecimalField(blank=True, decimal_places=2, help_text="Valeur au moment de l'acquisition. Saisie manuelle.", max_digits=14, null=True)),
                ('valeur_actuelle', models.DecimalField(decimal_places=2, default=0, help_text='Valeur estimative actuelle. Saisie manuelle — jamais une vérité comptable.', max_digits=14)),
                ('date_valorisation', models.DateField(blank=True, help_text='Date de la dernière valorisation manuelle.', null=True)),
                ('actif', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('compte_associe', models.ForeignKey(blank=True, help_text='Compte bancaire associé à cet actif (optionnel).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actifs', to='comptes.compte')),
                ('devise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actifs', to='referentiels.devise')),
                ('fiscalite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actifs', to='referentiels.fiscalite')),
            ],
            options={
                'verbose_name': 'Actif patrimonial',
                'verbose_name_plural': 'Actifs patrimoniaux',
                'ordering': ['type_actif', 'nom'],
                'abstract': False,
                'indexes': [models.Index(fields=['type_actif'], name='patrimoine__type_ac_063cee_idx'), models.Index(fields=['actif'], name='patrimoine__actif_99bc56_idx')],
            },
        ),
    ]
