# Generated by Django 6.0.6 on 2026-06-09 18:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimoine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueValorisation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('valeur', models.DecimalField(decimal_places=2, help_text='Valeur estimative enregistrée à cette date.', max_digits=14)),
                ('date_valorisation', models.DateField(help_text='Date à laquelle cette valeur a été constatée.')),
                ('actif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_valorisations', to='patrimoine.actif')),
            ],
            options={
                'verbose_name': 'Historique de valorisation',
                'verbose_name_plural': 'Historiques de valorisation',
                'ordering': ['-date_valorisation', '-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['actif', 'date_valorisation'], name='patrimoine__actif_i_5eb8b3_idx')],
            },
        ),
    ]
