# Generated by Django 6.0.6 on 2026-06-09 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimoine', '0002_historiquevalorisation'),
        ('referentiels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actif',
            name='frequence_valorisation',
            field=models.ForeignKey(blank=True, help_text='Fréquence à laquelle cet actif doit être re-valorisé. Null = pas de rappel.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actifs_a_valoriser', to='referentiels.frequence'),
        ),
        migrations.AddField(
            model_name='actif',
            name='rappel_jours_avant',
            field=models.PositiveSmallIntegerField(default=7, help_text="Nombre de jours avant l'échéance pour déclencher le rappel."),
        ),
    ]
