# Generated by Django 6.0.6 on 2026-06-08 21:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flux', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('montant', models.DecimalField(decimal_places=2, help_text='Montant transféré (toujours positif).', max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('flux_credit', models.OneToOneField(help_text='Flux positif sur le compte destination.', on_delete=django.db.models.deletion.PROTECT, related_name='transfert_credit', to='flux.flux')),
                ('flux_debit', models.OneToOneField(help_text='Flux négatif sur le compte source.', on_delete=django.db.models.deletion.PROTECT, related_name='transfert_debit', to='flux.flux')),
            ],
            options={
                'verbose_name': 'Transfert',
                'verbose_name_plural': 'Transferts',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
