# Generated by Django 6.0.6 on 2026-06-08 20:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('actif', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, help_text='Null = catégorie racine. Renseigné = sous-catégorie.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sous_categories', to='categories.categorie')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['ordre', 'nom'],
                'abstract': False,
            },
        ),
    ]
