# Generated by Django 6.0.6 on 2026-06-09 07:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('abonnements', '0001_initial'),
        ('budgets', '0001_initial'),
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('type_alerte', models.CharField(choices=[('BUDGET_DEPASSE', 'Budget dépassé'), ('BUDGET_ALERTE', 'Budget en alerte (seuil approche)'), ('SOLDE_BAS', 'Solde bas'), ('ABONNEMENT_EN_RETARD', 'Abonnement en retard'), ('ABONNEMENT_DIVERGENCE', 'Divergence de montant abonnement'), ('ECART_SOLDE', 'Écart de solde inhabituel')], max_length=50)),
                ('niveau', models.CharField(choices=[('INFO', 'Information'), ('AVERTISSEMENT', 'Avertissement'), ('CRITIQUE', 'Critique')], default='AVERTISSEMENT', max_length=20)),
                ('explication', models.TextField(help_text='Description factuelle et neutre de la situation détectée.')),
                ('valeur_constatee', models.DecimalField(blank=True, decimal_places=2, help_text='Valeur mesurée au moment de la détection.', max_digits=12, null=True)),
                ('valeur_seuil', models.DecimalField(blank=True, decimal_places=2, help_text='Seuil configuré au moment de la détection.', max_digits=12, null=True)),
                ('acquittee', models.BooleanField(default=False, help_text="True si l'utilisateur a pris connaissance de l'alerte.")),
                ('acquittee_le', models.DateTimeField(blank=True, editable=False, null=True)),
                ('abonnement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='abonnements.abonnement')),
                ('budget', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='budgets.budget')),
                ('compte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='comptes.compte')),
            ],
            options={
                'verbose_name': 'Alerte',
                'verbose_name_plural': 'Alertes',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['type_alerte', 'acquittee'], name='alertes_ale_type_al_fba571_idx'), models.Index(fields=['compte'], name='alertes_ale_compte__28b822_idx'), models.Index(fields=['budget'], name='alertes_ale_budget__682098_idx'), models.Index(fields=['abonnement'], name='alertes_ale_abonnem_0ec1eb_idx')],
            },
        ),
    ]
