# Generated by Django 6.0.6 on 2026-06-09 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonnements', '0001_initial'),
        ('alertes', '0001_initial'),
        ('budgets', '0001_initial'),
        ('comptes', '0001_initial'),
        ('patrimoine', '0002_historiquevalorisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerte',
            name='actif',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='patrimoine.actif'),
        ),
        migrations.AddIndex(
            model_name='alerte',
            index=models.Index(fields=['actif'], name='alertes_ale_actif_i_626699_idx'),
        ),
    ]
