# Generated by Django 6.0.6 on 2026-08-21 16:29

from django.db import migrations, models


def resorber_les_doublons(apps, schema_editor):
    """
    Acquitte les alertes ouvertes en double, en gardant **la plus récente**.

    ⚠️ Sans cette étape, `AddConstraint` échoue : la contrainte ne peut pas se
    poser sur une table qui la viole déjà. Le dédoublonnage n'était qu'un
    `exists()` suivi d'un `create()` — deux appels concurrents créaient deux
    alertes identiques (D27 de la revue UI/UX du 2026-08-20).

    ⚠️ **On acquitte, on ne supprime pas.** Une alerte est un enregistrement
    daté ; la plus ancienne du groupe raconte quand la situation a été détectée
    pour la première fois. La faire disparaître réécrirait l'histoire — ce que
    le dépôt refuse partout ailleurs (soft delete, compensation, ADR marqué
    *Remplacé*). Elle sort simplement des écrans « non acquittées », comme le
    veut ADR-0067.
    """
    from django.db.models import Count
    from django.utils import timezone

    Alerte = apps.get_model("alertes", "Alerte")
    maintenant = timezone.now()
    cles = ("type_alerte", "compte_id", "budget_id", "abonnement_id", "actif_id")

    groupes = (
        Alerte.objects.filter(acquittee=False, is_deleted=False)
        .values(*cles)
        .annotate(n=Count("id"))
        .filter(n__gt=1)
    )

    total = 0
    for groupe in groupes:
        filtre = {c: groupe[c] for c in cles}
        doublons = (
            Alerte.objects.filter(acquittee=False, is_deleted=False, **filtre)
            .order_by("-created_at", "-id")
        )
        # `[1:]` : tout sauf la plus récente. `list()` d'abord — un `update()`
        # sur un queryset tranché n'est pas permis.
        a_acquitter = [a.pk for a in doublons[1:]]
        if a_acquitter:
            total += Alerte.objects.filter(pk__in=a_acquitter).update(
                acquittee=True, acquittee_le=maintenant, updated_at=maintenant
            )

    if total:
        print(f"  {total} alerte(s) en double acquittée(s) avant la contrainte.")


def ne_rien_defaire(apps, schema_editor):
    """
    Irréversible **par choix** : rien ne distingue une alerte acquittée par
    cette migration d'une alerte acquittée par quelqu'un. Les rouvrir toutes
    serait pire que de ne rien faire.
    """


class Migration(migrations.Migration):

    dependencies = [
        ('abonnements', '0001_initial'),
        ('alertes', '0002_alerte_actif_alerte_alertes_ale_actif_i_626699_idx'),
        ('budgets', '0006_budget_en_jeu_budget_points_alloues_and_more'),
        ('comptes', '0006_alter_compte_code'),
        ('patrimoine', '0003_actif_frequence_valorisation_and_more'),
    ]

    operations = [
        # L'ordre compte : la contrainte ne peut pas se poser sur une table qui
        # la viole déjà.
        migrations.RunPython(resorber_les_doublons, ne_rien_defaire),
        migrations.AddConstraint(
            model_name='alerte',
            constraint=models.UniqueConstraint(models.F('type_alerte'), models.F('compte'), models.F('budget'), models.F('abonnement'), models.F('actif'), condition=models.Q(('acquittee', False), ('is_deleted', False)), name='alerte_ouverte_unique_par_cible', nulls_distinct=False),
        ),
    ]
