# Generated by Django 6.0.6 on 2026-07-18 08:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comptes', '0005_init_est_epargne_from_type'),
        ('flux', '0003_flux_abonnement'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBancaire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('banque', models.CharField(choices=[('boursobank', 'BoursoBank')], default='boursobank', max_length=30)),
                ('nom_fichier', models.CharField(blank=True, max_length=255)),
                ('compte_num_source', models.CharField(blank=True, max_length=50)),
                ('nb_lignes', models.PositiveIntegerField(default=0)),
                ('nb_rapproches', models.PositiveIntegerField(default=0)),
                ('nb_manquants_app', models.PositiveIntegerField(default=0)),
                ('nb_ambigus', models.PositiveIntegerField(default=0)),
                ('nb_ignores', models.PositiveIntegerField(default=0)),
                ('nb_doublons_ignores', models.PositiveIntegerField(default=0, help_text='Lignes déjà présentes dans un import précédent (anti-doublon).')),
                ('notes', models.TextField(blank=True)),
                ('compte', models.ForeignKey(help_text="Compte de l'app auquel ce relevé est rattaché (choix manuel).", on_delete=django.db.models.deletion.PROTECT, related_name='imports_bancaires', to='comptes.compte')),
            ],
            options={
                'verbose_name': 'Import bancaire',
                'verbose_name_plural': 'Imports bancaires',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LigneBancaire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('date_operation', models.DateField()),
                ('date_valeur', models.DateField()),
                ('libelle', models.CharField(max_length=255)),
                ('libelle_suggere', models.CharField(blank=True, max_length=255)),
                ('categorie_banque', models.CharField(blank=True, max_length=120)),
                ('categorie_parent_banque', models.CharField(blank=True, max_length=120)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('commentaire', models.TextField(blank=True)),
                ('solde_apres', models.DecimalField(blank=True, decimal_places=2, help_text="Solde du compte après l'opération (accountbalance) — contrôle du solde_reel du jour.", max_digits=12, null=True)),
                ('pointe_banque', models.BooleanField(default=False, help_text='Pointage côté banque (colonne mark).')),
                ('hash_dedup', models.CharField(db_index=True, max_length=40)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('rapproche', 'Rapproché'), ('manquant_app', "Manquant dans l'app"), ('ambigu', 'Ambigu'), ('ignore', 'Ignoré')], db_index=True, default='en_attente', max_length=20)),
                ('flux', models.ForeignKey(blank=True, help_text="Flux de l'app apparié par le rapprochement, si trouvé.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_bancaires', to='flux.flux')),
                ('import_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='imports.importbancaire')),
            ],
            options={
                'verbose_name': 'Ligne bancaire',
                'verbose_name_plural': 'Lignes bancaires',
                'ordering': ['-date_operation', '-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['import_lot', 'statut'], name='imports_lig_import__e7e01f_idx'), models.Index(fields=['date_operation', 'montant'], name='imports_lig_date_op_d4ec91_idx')],
            },
        ),
    ]
